{% set name = "mdurl" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdurl-{{ version }}.tar.gz
  sha256: 94873a969008ee48880fb21bad7de0349fef529f3be178969af5817239e9b990

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2.0,<4
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mdurl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/mdurl
  summary: Markdown URL utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - chrisjsewell
    - thewchan
