{% set name = "mdurl" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb413d29f5eea38f31dd4754dd7377d4465116fb207585f97bf925588687c1ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2.0,<4
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - mdurl

about:
  home: https://github.com/executablebooks/mdurl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: URL utilities for markdown-it-py parser.

extra:
  recipe-maintainers:
    - chrisjsewell
