{% set name = "mdurl" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdurl-{{ version }}.tar.gz
  sha256: bb413d29f5eea38f31dd4754dd7377d4465116fb207585f97bf925588687c1ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2.0,<4
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mdurl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/mdurl
  summary: Markdown URL utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - chrisjsewell
    - thewchan
